// Code generated by protoc-gen-go. DO NOT EDIT.
// source: calculator/calculatorpb/calculator.proto

package calculatorpb

import (
	context "context"
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type Request struct {
	A                    int32    `protobuf:"varint,1,opt,name=a,proto3" json:"a,omitempty"`
	B                    int32    `protobuf:"varint,2,opt,name=b,proto3" json:"b,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Request) Reset()         { *m = Request{} }
func (m *Request) String() string { return proto.CompactTextString(m) }
func (*Request) ProtoMessage()    {}
func (*Request) Descriptor() ([]byte, []int) {
	return fileDescriptor_7f42938f8c8365cf, []int{0}
}

func (m *Request) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Request.Unmarshal(m, b)
}
func (m *Request) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Request.Marshal(b, m, deterministic)
}
func (m *Request) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Request.Merge(m, src)
}
func (m *Request) XXX_Size() int {
	return xxx_messageInfo_Request.Size(m)
}
func (m *Request) XXX_DiscardUnknown() {
	xxx_messageInfo_Request.DiscardUnknown(m)
}

var xxx_messageInfo_Request proto.InternalMessageInfo

func (m *Request) GetA() int32 {
	if m != nil {
		return m.A
	}
	return 0
}

func (m *Request) GetB() int32 {
	if m != nil {
		return m.B
	}
	return 0
}

type Response struct {
	Ans                  int32    `protobuf:"varint,1,opt,name=ans,proto3" json:"ans,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Response) Reset()         { *m = Response{} }
func (m *Response) String() string { return proto.CompactTextString(m) }
func (*Response) ProtoMessage()    {}
func (*Response) Descriptor() ([]byte, []int) {
	return fileDescriptor_7f42938f8c8365cf, []int{1}
}

func (m *Response) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Response.Unmarshal(m, b)
}
func (m *Response) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Response.Marshal(b, m, deterministic)
}
func (m *Response) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Response.Merge(m, src)
}
func (m *Response) XXX_Size() int {
	return xxx_messageInfo_Response.Size(m)
}
func (m *Response) XXX_DiscardUnknown() {
	xxx_messageInfo_Response.DiscardUnknown(m)
}

var xxx_messageInfo_Response proto.InternalMessageInfo

func (m *Response) GetAns() int32 {
	if m != nil {
		return m.Ans
	}
	return 0
}

type PrimeNoDecompositionRequest struct {
	N                    int32    `protobuf:"varint,1,opt,name=n,proto3" json:"n,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *PrimeNoDecompositionRequest) Reset()         { *m = PrimeNoDecompositionRequest{} }
func (m *PrimeNoDecompositionRequest) String() string { return proto.CompactTextString(m) }
func (*PrimeNoDecompositionRequest) ProtoMessage()    {}
func (*PrimeNoDecompositionRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_7f42938f8c8365cf, []int{2}
}

func (m *PrimeNoDecompositionRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_PrimeNoDecompositionRequest.Unmarshal(m, b)
}
func (m *PrimeNoDecompositionRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_PrimeNoDecompositionRequest.Marshal(b, m, deterministic)
}
func (m *PrimeNoDecompositionRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_PrimeNoDecompositionRequest.Merge(m, src)
}
func (m *PrimeNoDecompositionRequest) XXX_Size() int {
	return xxx_messageInfo_PrimeNoDecompositionRequest.Size(m)
}
func (m *PrimeNoDecompositionRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_PrimeNoDecompositionRequest.DiscardUnknown(m)
}

var xxx_messageInfo_PrimeNoDecompositionRequest proto.InternalMessageInfo

func (m *PrimeNoDecompositionRequest) GetN() int32 {
	if m != nil {
		return m.N
	}
	return 0
}

type PrimeNoDecompositionResponse struct {
	N                    int32    `protobuf:"varint,1,opt,name=n,proto3" json:"n,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *PrimeNoDecompositionResponse) Reset()         { *m = PrimeNoDecompositionResponse{} }
func (m *PrimeNoDecompositionResponse) String() string { return proto.CompactTextString(m) }
func (*PrimeNoDecompositionResponse) ProtoMessage()    {}
func (*PrimeNoDecompositionResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_7f42938f8c8365cf, []int{3}
}

func (m *PrimeNoDecompositionResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_PrimeNoDecompositionResponse.Unmarshal(m, b)
}
func (m *PrimeNoDecompositionResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_PrimeNoDecompositionResponse.Marshal(b, m, deterministic)
}
func (m *PrimeNoDecompositionResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_PrimeNoDecompositionResponse.Merge(m, src)
}
func (m *PrimeNoDecompositionResponse) XXX_Size() int {
	return xxx_messageInfo_PrimeNoDecompositionResponse.Size(m)
}
func (m *PrimeNoDecompositionResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_PrimeNoDecompositionResponse.DiscardUnknown(m)
}

var xxx_messageInfo_PrimeNoDecompositionResponse proto.InternalMessageInfo

func (m *PrimeNoDecompositionResponse) GetN() int32 {
	if m != nil {
		return m.N
	}
	return 0
}

type GetAvgRequest struct {
	N                    int32    `protobuf:"varint,1,opt,name=n,proto3" json:"n,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *GetAvgRequest) Reset()         { *m = GetAvgRequest{} }
func (m *GetAvgRequest) String() string { return proto.CompactTextString(m) }
func (*GetAvgRequest) ProtoMessage()    {}
func (*GetAvgRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_7f42938f8c8365cf, []int{4}
}

func (m *GetAvgRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GetAvgRequest.Unmarshal(m, b)
}
func (m *GetAvgRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GetAvgRequest.Marshal(b, m, deterministic)
}
func (m *GetAvgRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GetAvgRequest.Merge(m, src)
}
func (m *GetAvgRequest) XXX_Size() int {
	return xxx_messageInfo_GetAvgRequest.Size(m)
}
func (m *GetAvgRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_GetAvgRequest.DiscardUnknown(m)
}

var xxx_messageInfo_GetAvgRequest proto.InternalMessageInfo

func (m *GetAvgRequest) GetN() int32 {
	if m != nil {
		return m.N
	}
	return 0
}

type GetAvgResponse struct {
	N                    float32  `protobuf:"fixed32,1,opt,name=n,proto3" json:"n,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *GetAvgResponse) Reset()         { *m = GetAvgResponse{} }
func (m *GetAvgResponse) String() string { return proto.CompactTextString(m) }
func (*GetAvgResponse) ProtoMessage()    {}
func (*GetAvgResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_7f42938f8c8365cf, []int{5}
}

func (m *GetAvgResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GetAvgResponse.Unmarshal(m, b)
}
func (m *GetAvgResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GetAvgResponse.Marshal(b, m, deterministic)
}
func (m *GetAvgResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GetAvgResponse.Merge(m, src)
}
func (m *GetAvgResponse) XXX_Size() int {
	return xxx_messageInfo_GetAvgResponse.Size(m)
}
func (m *GetAvgResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_GetAvgResponse.DiscardUnknown(m)
}

var xxx_messageInfo_GetAvgResponse proto.InternalMessageInfo

func (m *GetAvgResponse) GetN() float32 {
	if m != nil {
		return m.N
	}
	return 0
}

type GetMaxRequest struct {
	N                    int32    `protobuf:"varint,1,opt,name=n,proto3" json:"n,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *GetMaxRequest) Reset()         { *m = GetMaxRequest{} }
func (m *GetMaxRequest) String() string { return proto.CompactTextString(m) }
func (*GetMaxRequest) ProtoMessage()    {}
func (*GetMaxRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_7f42938f8c8365cf, []int{6}
}

func (m *GetMaxRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GetMaxRequest.Unmarshal(m, b)
}
func (m *GetMaxRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GetMaxRequest.Marshal(b, m, deterministic)
}
func (m *GetMaxRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GetMaxRequest.Merge(m, src)
}
func (m *GetMaxRequest) XXX_Size() int {
	return xxx_messageInfo_GetMaxRequest.Size(m)
}
func (m *GetMaxRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_GetMaxRequest.DiscardUnknown(m)
}

var xxx_messageInfo_GetMaxRequest proto.InternalMessageInfo

func (m *GetMaxRequest) GetN() int32 {
	if m != nil {
		return m.N
	}
	return 0
}

type GetMaxResponse struct {
	N                    int32    `protobuf:"varint,1,opt,name=n,proto3" json:"n,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *GetMaxResponse) Reset()         { *m = GetMaxResponse{} }
func (m *GetMaxResponse) String() string { return proto.CompactTextString(m) }
func (*GetMaxResponse) ProtoMessage()    {}
func (*GetMaxResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_7f42938f8c8365cf, []int{7}
}

func (m *GetMaxResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GetMaxResponse.Unmarshal(m, b)
}
func (m *GetMaxResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GetMaxResponse.Marshal(b, m, deterministic)
}
func (m *GetMaxResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GetMaxResponse.Merge(m, src)
}
func (m *GetMaxResponse) XXX_Size() int {
	return xxx_messageInfo_GetMaxResponse.Size(m)
}
func (m *GetMaxResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_GetMaxResponse.DiscardUnknown(m)
}

var xxx_messageInfo_GetMaxResponse proto.InternalMessageInfo

func (m *GetMaxResponse) GetN() int32 {
	if m != nil {
		return m.N
	}
	return 0
}

type SquareRootRequest struct {
	N                    int32    `protobuf:"varint,1,opt,name=n,proto3" json:"n,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *SquareRootRequest) Reset()         { *m = SquareRootRequest{} }
func (m *SquareRootRequest) String() string { return proto.CompactTextString(m) }
func (*SquareRootRequest) ProtoMessage()    {}
func (*SquareRootRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_7f42938f8c8365cf, []int{8}
}

func (m *SquareRootRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_SquareRootRequest.Unmarshal(m, b)
}
func (m *SquareRootRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_SquareRootRequest.Marshal(b, m, deterministic)
}
func (m *SquareRootRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_SquareRootRequest.Merge(m, src)
}
func (m *SquareRootRequest) XXX_Size() int {
	return xxx_messageInfo_SquareRootRequest.Size(m)
}
func (m *SquareRootRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_SquareRootRequest.DiscardUnknown(m)
}

var xxx_messageInfo_SquareRootRequest proto.InternalMessageInfo

func (m *SquareRootRequest) GetN() int32 {
	if m != nil {
		return m.N
	}
	return 0
}

type SquareRootResponse struct {
	N                    float64  `protobuf:"fixed64,1,opt,name=n,proto3" json:"n,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *SquareRootResponse) Reset()         { *m = SquareRootResponse{} }
func (m *SquareRootResponse) String() string { return proto.CompactTextString(m) }
func (*SquareRootResponse) ProtoMessage()    {}
func (*SquareRootResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_7f42938f8c8365cf, []int{9}
}

func (m *SquareRootResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_SquareRootResponse.Unmarshal(m, b)
}
func (m *SquareRootResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_SquareRootResponse.Marshal(b, m, deterministic)
}
func (m *SquareRootResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_SquareRootResponse.Merge(m, src)
}
func (m *SquareRootResponse) XXX_Size() int {
	return xxx_messageInfo_SquareRootResponse.Size(m)
}
func (m *SquareRootResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_SquareRootResponse.DiscardUnknown(m)
}

var xxx_messageInfo_SquareRootResponse proto.InternalMessageInfo

func (m *SquareRootResponse) GetN() float64 {
	if m != nil {
		return m.N
	}
	return 0
}

func init() {
	proto.RegisterType((*Request)(nil), "Request")
	proto.RegisterType((*Response)(nil), "Response")
	proto.RegisterType((*PrimeNoDecompositionRequest)(nil), "PrimeNoDecompositionRequest")
	proto.RegisterType((*PrimeNoDecompositionResponse)(nil), "PrimeNoDecompositionResponse")
	proto.RegisterType((*GetAvgRequest)(nil), "GetAvgRequest")
	proto.RegisterType((*GetAvgResponse)(nil), "GetAvgResponse")
	proto.RegisterType((*GetMaxRequest)(nil), "GetMaxRequest")
	proto.RegisterType((*GetMaxResponse)(nil), "GetMaxResponse")
	proto.RegisterType((*SquareRootRequest)(nil), "SquareRootRequest")
	proto.RegisterType((*SquareRootResponse)(nil), "SquareRootResponse")
}

func init() {
	proto.RegisterFile("calculator/calculatorpb/calculator.proto", fileDescriptor_7f42938f8c8365cf)
}

var fileDescriptor_7f42938f8c8365cf = []byte{
	// 317 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x7c, 0x92, 0x4d, 0x4b, 0xc3, 0x40,
	0x10, 0x86, 0xb3, 0x2d, 0xd6, 0x76, 0xa8, 0x55, 0x47, 0x0f, 0x25, 0xa6, 0xa2, 0x0b, 0x42, 0x41,
	0xdd, 0x16, 0x3d, 0x79, 0xac, 0x0a, 0x3d, 0x55, 0x24, 0x3d, 0x08, 0xde, 0x36, 0xed, 0x22, 0x81,
	0x76, 0x37, 0x1f, 0x1b, 0xe9, 0x9f, 0xf1, 0xbf, 0x4a, 0xbe, 0x48, 0xd2, 0x86, 0xdc, 0x76, 0x98,
	0xe7, 0x7d, 0x17, 0x1e, 0x06, 0xc6, 0x2b, 0xbe, 0x59, 0x45, 0x1b, 0xae, 0x55, 0x30, 0x29, 0x9e,
	0x9e, 0x53, 0x1a, 0x98, 0x17, 0x28, 0xad, 0xe8, 0x1d, 0x1c, 0xdb, 0xc2, 0x8f, 0x44, 0xa8, 0xb1,
	0x0f, 0x84, 0x0f, 0xc9, 0x0d, 0x19, 0x1f, 0xd9, 0x84, 0xc7, 0x93, 0x33, 0x6c, 0xa5, 0x93, 0x43,
	0x2d, 0xe8, 0xda, 0x22, 0xf4, 0x94, 0x0c, 0x05, 0x9e, 0x41, 0x9b, 0xcb, 0x30, 0x23, 0xe3, 0x27,
	0xbd, 0x87, 0xab, 0xcf, 0xc0, 0xdd, 0x8a, 0x0f, 0xf5, 0x2e, 0x56, 0x6a, 0xeb, 0xa9, 0xd0, 0xd5,
	0xae, 0x92, 0xa5, 0x62, 0x99, 0x17, 0x4b, 0xfa, 0x00, 0x56, 0x3d, 0x9c, 0xd5, 0x57, 0xe9, 0x11,
	0x9c, 0xcc, 0x85, 0x9e, 0xfd, 0xfe, 0xd4, 0x97, 0x5d, 0xc3, 0x20, 0x5f, 0xef, 0xc7, 0x5b, 0x45,
	0x7c, 0xc1, 0x77, 0x4d, 0xf1, 0x64, 0x5d, 0xfb, 0xfb, 0x2d, 0x9c, 0x2f, 0xfd, 0x88, 0x07, 0xc2,
	0x56, 0x4a, 0xd7, 0x57, 0x50, 0xc0, 0x32, 0xb2, 0x5f, 0x43, 0x6c, 0x22, 0x9f, 0xfe, 0x5a, 0xd0,
	0x7b, 0xcb, 0xcc, 0x0b, 0xb4, 0xa0, 0x3d, 0x5b, 0xaf, 0xb1, 0xcb, 0xb2, 0x42, 0xb3, 0xc7, 0xf2,
	0x1c, 0x35, 0xf0, 0x0b, 0x2e, 0xeb, 0xf4, 0xa0, 0xc5, 0x1a, 0x14, 0x9b, 0x23, 0xd6, 0xe4, 0x94,
	0x1a, 0x53, 0x82, 0x8f, 0xd0, 0x49, 0x55, 0xe1, 0x80, 0x55, 0x94, 0x9a, 0xa7, 0xac, 0xea, 0x90,
	0x1a, 0x63, 0x82, 0x93, 0x04, 0x5f, 0xf0, 0x5d, 0x8a, 0x17, 0x0a, 0x53, 0xbc, 0xe4, 0x2c, 0xc6,
	0xa7, 0x04, 0x5f, 0xa0, 0x3f, 0x17, 0x7a, 0xe9, 0x47, 0xa9, 0x0a, 0x44, 0x76, 0xa0, 0xce, 0xbc,
	0x60, 0x87, 0xae, 0xa8, 0xf1, 0x3a, 0xf8, 0xee, 0x97, 0xaf, 0xd4, 0xe9, 0x24, 0xb7, 0xf9, 0xfc,
	0x1f, 0x00, 0x00, 0xff, 0xff, 0xd7, 0x34, 0x65, 0xe5, 0xc7, 0x02, 0x00, 0x00,
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConnInterface

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion6

// CalculateClient is the client API for Calculate service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type CalculateClient interface {
	// Unary
	Add(ctx context.Context, in *Request, opts ...grpc.CallOption) (*Response, error)
	// Server side streaming
	PrimeNoDecomposition(ctx context.Context, in *PrimeNoDecompositionRequest, opts ...grpc.CallOption) (Calculate_PrimeNoDecompositionClient, error)
	// client side streaming
	GetAvg(ctx context.Context, opts ...grpc.CallOption) (Calculate_GetAvgClient, error)
	// get maximum of the input stream everytime
	GetMax(ctx context.Context, opts ...grpc.CallOption) (Calculate_GetMaxClient, error)
	// Unary API for square root
	GetSqureRoot(ctx context.Context, in *SquareRootRequest, opts ...grpc.CallOption) (*SquareRootResponse, error)
}

type calculateClient struct {
	cc grpc.ClientConnInterface
}

func NewCalculateClient(cc grpc.ClientConnInterface) CalculateClient {
	return &calculateClient{cc}
}

func (c *calculateClient) Add(ctx context.Context, in *Request, opts ...grpc.CallOption) (*Response, error) {
	out := new(Response)
	err := c.cc.Invoke(ctx, "/Calculate/Add", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *calculateClient) PrimeNoDecomposition(ctx context.Context, in *PrimeNoDecompositionRequest, opts ...grpc.CallOption) (Calculate_PrimeNoDecompositionClient, error) {
	stream, err := c.cc.NewStream(ctx, &_Calculate_serviceDesc.Streams[0], "/Calculate/PrimeNoDecomposition", opts...)
	if err != nil {
		return nil, err
	}
	x := &calculatePrimeNoDecompositionClient{stream}
	if err := x.ClientStream.SendMsg(in); err != nil {
		return nil, err
	}
	if err := x.ClientStream.CloseSend(); err != nil {
		return nil, err
	}
	return x, nil
}

type Calculate_PrimeNoDecompositionClient interface {
	Recv() (*PrimeNoDecompositionResponse, error)
	grpc.ClientStream
}

type calculatePrimeNoDecompositionClient struct {
	grpc.ClientStream
}

func (x *calculatePrimeNoDecompositionClient) Recv() (*PrimeNoDecompositionResponse, error) {
	m := new(PrimeNoDecompositionResponse)
	if err := x.ClientStream.RecvMsg(m); err != nil {
		return nil, err
	}
	return m, nil
}

func (c *calculateClient) GetAvg(ctx context.Context, opts ...grpc.CallOption) (Calculate_GetAvgClient, error) {
	stream, err := c.cc.NewStream(ctx, &_Calculate_serviceDesc.Streams[1], "/Calculate/GetAvg", opts...)
	if err != nil {
		return nil, err
	}
	x := &calculateGetAvgClient{stream}
	return x, nil
}

type Calculate_GetAvgClient interface {
	Send(*GetAvgRequest) error
	CloseAndRecv() (*GetAvgResponse, error)
	grpc.ClientStream
}

type calculateGetAvgClient struct {
	grpc.ClientStream
}

func (x *calculateGetAvgClient) Send(m *GetAvgRequest) error {
	return x.ClientStream.SendMsg(m)
}

func (x *calculateGetAvgClient) CloseAndRecv() (*GetAvgResponse, error) {
	if err := x.ClientStream.CloseSend(); err != nil {
		return nil, err
	}
	m := new(GetAvgResponse)
	if err := x.ClientStream.RecvMsg(m); err != nil {
		return nil, err
	}
	return m, nil
}

func (c *calculateClient) GetMax(ctx context.Context, opts ...grpc.CallOption) (Calculate_GetMaxClient, error) {
	stream, err := c.cc.NewStream(ctx, &_Calculate_serviceDesc.Streams[2], "/Calculate/GetMax", opts...)
	if err != nil {
		return nil, err
	}
	x := &calculateGetMaxClient{stream}
	return x, nil
}

type Calculate_GetMaxClient interface {
	Send(*GetMaxRequest) error
	Recv() (*GetMaxResponse, error)
	grpc.ClientStream
}

type calculateGetMaxClient struct {
	grpc.ClientStream
}

func (x *calculateGetMaxClient) Send(m *GetMaxRequest) error {
	return x.ClientStream.SendMsg(m)
}

func (x *calculateGetMaxClient) Recv() (*GetMaxResponse, error) {
	m := new(GetMaxResponse)
	if err := x.ClientStream.RecvMsg(m); err != nil {
		return nil, err
	}
	return m, nil
}

func (c *calculateClient) GetSqureRoot(ctx context.Context, in *SquareRootRequest, opts ...grpc.CallOption) (*SquareRootResponse, error) {
	out := new(SquareRootResponse)
	err := c.cc.Invoke(ctx, "/Calculate/GetSqureRoot", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// CalculateServer is the server API for Calculate service.
type CalculateServer interface {
	// Unary
	Add(context.Context, *Request) (*Response, error)
	// Server side streaming
	PrimeNoDecomposition(*PrimeNoDecompositionRequest, Calculate_PrimeNoDecompositionServer) error
	// client side streaming
	GetAvg(Calculate_GetAvgServer) error
	// get maximum of the input stream everytime
	GetMax(Calculate_GetMaxServer) error
	// Unary API for square root
	GetSqureRoot(context.Context, *SquareRootRequest) (*SquareRootResponse, error)
}

// UnimplementedCalculateServer can be embedded to have forward compatible implementations.
type UnimplementedCalculateServer struct {
}

func (*UnimplementedCalculateServer) Add(ctx context.Context, req *Request) (*Response, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Add not implemented")
}
func (*UnimplementedCalculateServer) PrimeNoDecomposition(req *PrimeNoDecompositionRequest, srv Calculate_PrimeNoDecompositionServer) error {
	return status.Errorf(codes.Unimplemented, "method PrimeNoDecomposition not implemented")
}
func (*UnimplementedCalculateServer) GetAvg(srv Calculate_GetAvgServer) error {
	return status.Errorf(codes.Unimplemented, "method GetAvg not implemented")
}
func (*UnimplementedCalculateServer) GetMax(srv Calculate_GetMaxServer) error {
	return status.Errorf(codes.Unimplemented, "method GetMax not implemented")
}
func (*UnimplementedCalculateServer) GetSqureRoot(ctx context.Context, req *SquareRootRequest) (*SquareRootResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetSqureRoot not implemented")
}

func RegisterCalculateServer(s *grpc.Server, srv CalculateServer) {
	s.RegisterService(&_Calculate_serviceDesc, srv)
}

func _Calculate_Add_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(Request)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(CalculateServer).Add(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/Calculate/Add",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(CalculateServer).Add(ctx, req.(*Request))
	}
	return interceptor(ctx, in, info, handler)
}

func _Calculate_PrimeNoDecomposition_Handler(srv interface{}, stream grpc.ServerStream) error {
	m := new(PrimeNoDecompositionRequest)
	if err := stream.RecvMsg(m); err != nil {
		return err
	}
	return srv.(CalculateServer).PrimeNoDecomposition(m, &calculatePrimeNoDecompositionServer{stream})
}

type Calculate_PrimeNoDecompositionServer interface {
	Send(*PrimeNoDecompositionResponse) error
	grpc.ServerStream
}

type calculatePrimeNoDecompositionServer struct {
	grpc.ServerStream
}

func (x *calculatePrimeNoDecompositionServer) Send(m *PrimeNoDecompositionResponse) error {
	return x.ServerStream.SendMsg(m)
}

func _Calculate_GetAvg_Handler(srv interface{}, stream grpc.ServerStream) error {
	return srv.(CalculateServer).GetAvg(&calculateGetAvgServer{stream})
}

type Calculate_GetAvgServer interface {
	SendAndClose(*GetAvgResponse) error
	Recv() (*GetAvgRequest, error)
	grpc.ServerStream
}

type calculateGetAvgServer struct {
	grpc.ServerStream
}

func (x *calculateGetAvgServer) SendAndClose(m *GetAvgResponse) error {
	return x.ServerStream.SendMsg(m)
}

func (x *calculateGetAvgServer) Recv() (*GetAvgRequest, error) {
	m := new(GetAvgRequest)
	if err := x.ServerStream.RecvMsg(m); err != nil {
		return nil, err
	}
	return m, nil
}

func _Calculate_GetMax_Handler(srv interface{}, stream grpc.ServerStream) error {
	return srv.(CalculateServer).GetMax(&calculateGetMaxServer{stream})
}

type Calculate_GetMaxServer interface {
	Send(*GetMaxResponse) error
	Recv() (*GetMaxRequest, error)
	grpc.ServerStream
}

type calculateGetMaxServer struct {
	grpc.ServerStream
}

func (x *calculateGetMaxServer) Send(m *GetMaxResponse) error {
	return x.ServerStream.SendMsg(m)
}

func (x *calculateGetMaxServer) Recv() (*GetMaxRequest, error) {
	m := new(GetMaxRequest)
	if err := x.ServerStream.RecvMsg(m); err != nil {
		return nil, err
	}
	return m, nil
}

func _Calculate_GetSqureRoot_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(SquareRootRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(CalculateServer).GetSqureRoot(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/Calculate/GetSqureRoot",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(CalculateServer).GetSqureRoot(ctx, req.(*SquareRootRequest))
	}
	return interceptor(ctx, in, info, handler)
}

var _Calculate_serviceDesc = grpc.ServiceDesc{
	ServiceName: "Calculate",
	HandlerType: (*CalculateServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "Add",
			Handler:    _Calculate_Add_Handler,
		},
		{
			MethodName: "GetSqureRoot",
			Handler:    _Calculate_GetSqureRoot_Handler,
		},
	},
	Streams: []grpc.StreamDesc{
		{
			StreamName:    "PrimeNoDecomposition",
			Handler:       _Calculate_PrimeNoDecomposition_Handler,
			ServerStreams: true,
		},
		{
			StreamName:    "GetAvg",
			Handler:       _Calculate_GetAvg_Handler,
			ClientStreams: true,
		},
		{
			StreamName:    "GetMax",
			Handler:       _Calculate_GetMax_Handler,
			ServerStreams: true,
			ClientStreams: true,
		},
	},
	Metadata: "calculator/calculatorpb/calculator.proto",
}
