// Code generated by protoc-gen-go. DO NOT EDIT.
// source: calculator/calculatorpb/calculator.proto

package calculatorpb

import (
	context "context"
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type Request struct {
	A                    int32    `protobuf:"varint,1,opt,name=a,proto3" json:"a,omitempty"`
	B                    int32    `protobuf:"varint,2,opt,name=b,proto3" json:"b,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Request) Reset()         { *m = Request{} }
func (m *Request) String() string { return proto.CompactTextString(m) }
func (*Request) ProtoMessage()    {}
func (*Request) Descriptor() ([]byte, []int) {
	return fileDescriptor_7f42938f8c8365cf, []int{0}
}

func (m *Request) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Request.Unmarshal(m, b)
}
func (m *Request) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Request.Marshal(b, m, deterministic)
}
func (m *Request) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Request.Merge(m, src)
}
func (m *Request) XXX_Size() int {
	return xxx_messageInfo_Request.Size(m)
}
func (m *Request) XXX_DiscardUnknown() {
	xxx_messageInfo_Request.DiscardUnknown(m)
}

var xxx_messageInfo_Request proto.InternalMessageInfo

func (m *Request) GetA() int32 {
	if m != nil {
		return m.A
	}
	return 0
}

func (m *Request) GetB() int32 {
	if m != nil {
		return m.B
	}
	return 0
}

type Response struct {
	Ans                  int32    `protobuf:"varint,1,opt,name=ans,proto3" json:"ans,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Response) Reset()         { *m = Response{} }
func (m *Response) String() string { return proto.CompactTextString(m) }
func (*Response) ProtoMessage()    {}
func (*Response) Descriptor() ([]byte, []int) {
	return fileDescriptor_7f42938f8c8365cf, []int{1}
}

func (m *Response) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Response.Unmarshal(m, b)
}
func (m *Response) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Response.Marshal(b, m, deterministic)
}
func (m *Response) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Response.Merge(m, src)
}
func (m *Response) XXX_Size() int {
	return xxx_messageInfo_Response.Size(m)
}
func (m *Response) XXX_DiscardUnknown() {
	xxx_messageInfo_Response.DiscardUnknown(m)
}

var xxx_messageInfo_Response proto.InternalMessageInfo

func (m *Response) GetAns() int32 {
	if m != nil {
		return m.Ans
	}
	return 0
}

type PrimeNoDecompositionRequest struct {
	N                    int32    `protobuf:"varint,1,opt,name=n,proto3" json:"n,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *PrimeNoDecompositionRequest) Reset()         { *m = PrimeNoDecompositionRequest{} }
func (m *PrimeNoDecompositionRequest) String() string { return proto.CompactTextString(m) }
func (*PrimeNoDecompositionRequest) ProtoMessage()    {}
func (*PrimeNoDecompositionRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_7f42938f8c8365cf, []int{2}
}

func (m *PrimeNoDecompositionRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_PrimeNoDecompositionRequest.Unmarshal(m, b)
}
func (m *PrimeNoDecompositionRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_PrimeNoDecompositionRequest.Marshal(b, m, deterministic)
}
func (m *PrimeNoDecompositionRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_PrimeNoDecompositionRequest.Merge(m, src)
}
func (m *PrimeNoDecompositionRequest) XXX_Size() int {
	return xxx_messageInfo_PrimeNoDecompositionRequest.Size(m)
}
func (m *PrimeNoDecompositionRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_PrimeNoDecompositionRequest.DiscardUnknown(m)
}

var xxx_messageInfo_PrimeNoDecompositionRequest proto.InternalMessageInfo

func (m *PrimeNoDecompositionRequest) GetN() int32 {
	if m != nil {
		return m.N
	}
	return 0
}

type PrimeNoDecompositionResponse struct {
	N                    int32    `protobuf:"varint,1,opt,name=n,proto3" json:"n,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *PrimeNoDecompositionResponse) Reset()         { *m = PrimeNoDecompositionResponse{} }
func (m *PrimeNoDecompositionResponse) String() string { return proto.CompactTextString(m) }
func (*PrimeNoDecompositionResponse) ProtoMessage()    {}
func (*PrimeNoDecompositionResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_7f42938f8c8365cf, []int{3}
}

func (m *PrimeNoDecompositionResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_PrimeNoDecompositionResponse.Unmarshal(m, b)
}
func (m *PrimeNoDecompositionResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_PrimeNoDecompositionResponse.Marshal(b, m, deterministic)
}
func (m *PrimeNoDecompositionResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_PrimeNoDecompositionResponse.Merge(m, src)
}
func (m *PrimeNoDecompositionResponse) XXX_Size() int {
	return xxx_messageInfo_PrimeNoDecompositionResponse.Size(m)
}
func (m *PrimeNoDecompositionResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_PrimeNoDecompositionResponse.DiscardUnknown(m)
}

var xxx_messageInfo_PrimeNoDecompositionResponse proto.InternalMessageInfo

func (m *PrimeNoDecompositionResponse) GetN() int32 {
	if m != nil {
		return m.N
	}
	return 0
}

type GetAvgRequest struct {
	N                    int32    `protobuf:"varint,1,opt,name=n,proto3" json:"n,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *GetAvgRequest) Reset()         { *m = GetAvgRequest{} }
func (m *GetAvgRequest) String() string { return proto.CompactTextString(m) }
func (*GetAvgRequest) ProtoMessage()    {}
func (*GetAvgRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_7f42938f8c8365cf, []int{4}
}

func (m *GetAvgRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GetAvgRequest.Unmarshal(m, b)
}
func (m *GetAvgRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GetAvgRequest.Marshal(b, m, deterministic)
}
func (m *GetAvgRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GetAvgRequest.Merge(m, src)
}
func (m *GetAvgRequest) XXX_Size() int {
	return xxx_messageInfo_GetAvgRequest.Size(m)
}
func (m *GetAvgRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_GetAvgRequest.DiscardUnknown(m)
}

var xxx_messageInfo_GetAvgRequest proto.InternalMessageInfo

func (m *GetAvgRequest) GetN() int32 {
	if m != nil {
		return m.N
	}
	return 0
}

type GetAvgResponse struct {
	N                    float32  `protobuf:"fixed32,1,opt,name=n,proto3" json:"n,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *GetAvgResponse) Reset()         { *m = GetAvgResponse{} }
func (m *GetAvgResponse) String() string { return proto.CompactTextString(m) }
func (*GetAvgResponse) ProtoMessage()    {}
func (*GetAvgResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_7f42938f8c8365cf, []int{5}
}

func (m *GetAvgResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GetAvgResponse.Unmarshal(m, b)
}
func (m *GetAvgResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GetAvgResponse.Marshal(b, m, deterministic)
}
func (m *GetAvgResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GetAvgResponse.Merge(m, src)
}
func (m *GetAvgResponse) XXX_Size() int {
	return xxx_messageInfo_GetAvgResponse.Size(m)
}
func (m *GetAvgResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_GetAvgResponse.DiscardUnknown(m)
}

var xxx_messageInfo_GetAvgResponse proto.InternalMessageInfo

func (m *GetAvgResponse) GetN() float32 {
	if m != nil {
		return m.N
	}
	return 0
}

func init() {
	proto.RegisterType((*Request)(nil), "Request")
	proto.RegisterType((*Response)(nil), "Response")
	proto.RegisterType((*PrimeNoDecompositionRequest)(nil), "PrimeNoDecompositionRequest")
	proto.RegisterType((*PrimeNoDecompositionResponse)(nil), "PrimeNoDecompositionResponse")
	proto.RegisterType((*GetAvgRequest)(nil), "GetAvgRequest")
	proto.RegisterType((*GetAvgResponse)(nil), "GetAvgResponse")
}

func init() {
	proto.RegisterFile("calculator/calculatorpb/calculator.proto", fileDescriptor_7f42938f8c8365cf)
}

var fileDescriptor_7f42938f8c8365cf = []byte{
	// 250 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xe2, 0xd2, 0x48, 0x4e, 0xcc, 0x49,
	0x2e, 0xcd, 0x49, 0x2c, 0xc9, 0x2f, 0xd2, 0x47, 0x30, 0x0b, 0x92, 0x90, 0x38, 0x7a, 0x05, 0x45,
	0xf9, 0x25, 0xf9, 0x4a, 0xaa, 0x5c, 0xec, 0x41, 0xa9, 0x85, 0xa5, 0xa9, 0xc5, 0x25, 0x42, 0x3c,
	0x5c, 0x8c, 0x89, 0x12, 0x8c, 0x0a, 0x8c, 0x1a, 0xac, 0x41, 0x8c, 0x89, 0x20, 0x5e, 0x92, 0x04,
	0x13, 0x84, 0x97, 0xa4, 0x24, 0xc3, 0xc5, 0x11, 0x94, 0x5a, 0x5c, 0x90, 0x9f, 0x57, 0x9c, 0x2a,
	0x24, 0xc0, 0xc5, 0x9c, 0x98, 0x57, 0x0c, 0x55, 0x09, 0x62, 0x2a, 0x69, 0x73, 0x49, 0x07, 0x14,
	0x65, 0xe6, 0xa6, 0xfa, 0xe5, 0xbb, 0xa4, 0x26, 0xe7, 0xe7, 0x16, 0xe4, 0x17, 0x67, 0x96, 0x64,
	0xe6, 0xe7, 0x21, 0x19, 0x9c, 0x07, 0x33, 0x38, 0x4f, 0x49, 0x87, 0x4b, 0x06, 0xbb, 0x62, 0xa8,
	0xf1, 0xa8, 0xaa, 0x65, 0xb9, 0x78, 0xdd, 0x53, 0x4b, 0x1c, 0xcb, 0xd2, 0xb1, 0x1b, 0x26, 0xc7,
	0xc5, 0x07, 0x93, 0x46, 0xd7, 0xce, 0x14, 0xc4, 0x98, 0x67, 0xb4, 0x91, 0x91, 0x8b, 0xd3, 0x19,
	0xea, 0xe7, 0x54, 0x21, 0x19, 0x2e, 0x66, 0xc7, 0x94, 0x14, 0x21, 0x0e, 0x3d, 0xa8, 0x61, 0x52,
	0x9c, 0x7a, 0x30, 0x7d, 0x4a, 0x0c, 0x42, 0xe1, 0x5c, 0x22, 0xd8, 0x1c, 0x26, 0x24, 0xa3, 0x87,
	0xc7, 0x73, 0x52, 0xb2, 0x7a, 0xf8, 0x7c, 0xa3, 0xc4, 0x60, 0xc0, 0x28, 0xa4, 0xcb, 0xc5, 0x06,
	0x71, 0xa4, 0x10, 0x9f, 0x1e, 0x8a, 0x67, 0xa4, 0xf8, 0xf5, 0x50, 0x5d, 0xaf, 0xc4, 0xa0, 0xc1,
	0xe8, 0xc4, 0x17, 0xc5, 0x83, 0x1c, 0x67, 0x49, 0x6c, 0xe0, 0x98, 0x32, 0x06, 0x04, 0x00, 0x00,
	0xff, 0xff, 0x41, 0xbf, 0x80, 0x79, 0xd5, 0x01, 0x00, 0x00,
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConnInterface

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion6

// CalculateClient is the client API for Calculate service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type CalculateClient interface {
	// Unary
	Add(ctx context.Context, in *Request, opts ...grpc.CallOption) (*Response, error)
	// Server side streaming
	PrimeNoDecomposition(ctx context.Context, in *PrimeNoDecompositionRequest, opts ...grpc.CallOption) (Calculate_PrimeNoDecompositionClient, error)
	// client side streaming
	GetAvg(ctx context.Context, opts ...grpc.CallOption) (Calculate_GetAvgClient, error)
}

type calculateClient struct {
	cc grpc.ClientConnInterface
}

func NewCalculateClient(cc grpc.ClientConnInterface) CalculateClient {
	return &calculateClient{cc}
}

func (c *calculateClient) Add(ctx context.Context, in *Request, opts ...grpc.CallOption) (*Response, error) {
	out := new(Response)
	err := c.cc.Invoke(ctx, "/Calculate/Add", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *calculateClient) PrimeNoDecomposition(ctx context.Context, in *PrimeNoDecompositionRequest, opts ...grpc.CallOption) (Calculate_PrimeNoDecompositionClient, error) {
	stream, err := c.cc.NewStream(ctx, &_Calculate_serviceDesc.Streams[0], "/Calculate/PrimeNoDecomposition", opts...)
	if err != nil {
		return nil, err
	}
	x := &calculatePrimeNoDecompositionClient{stream}
	if err := x.ClientStream.SendMsg(in); err != nil {
		return nil, err
	}
	if err := x.ClientStream.CloseSend(); err != nil {
		return nil, err
	}
	return x, nil
}

type Calculate_PrimeNoDecompositionClient interface {
	Recv() (*PrimeNoDecompositionResponse, error)
	grpc.ClientStream
}

type calculatePrimeNoDecompositionClient struct {
	grpc.ClientStream
}

func (x *calculatePrimeNoDecompositionClient) Recv() (*PrimeNoDecompositionResponse, error) {
	m := new(PrimeNoDecompositionResponse)
	if err := x.ClientStream.RecvMsg(m); err != nil {
		return nil, err
	}
	return m, nil
}

func (c *calculateClient) GetAvg(ctx context.Context, opts ...grpc.CallOption) (Calculate_GetAvgClient, error) {
	stream, err := c.cc.NewStream(ctx, &_Calculate_serviceDesc.Streams[1], "/Calculate/GetAvg", opts...)
	if err != nil {
		return nil, err
	}
	x := &calculateGetAvgClient{stream}
	return x, nil
}

type Calculate_GetAvgClient interface {
	Send(*GetAvgRequest) error
	CloseAndRecv() (*GetAvgResponse, error)
	grpc.ClientStream
}

type calculateGetAvgClient struct {
	grpc.ClientStream
}

func (x *calculateGetAvgClient) Send(m *GetAvgRequest) error {
	return x.ClientStream.SendMsg(m)
}

func (x *calculateGetAvgClient) CloseAndRecv() (*GetAvgResponse, error) {
	if err := x.ClientStream.CloseSend(); err != nil {
		return nil, err
	}
	m := new(GetAvgResponse)
	if err := x.ClientStream.RecvMsg(m); err != nil {
		return nil, err
	}
	return m, nil
}

// CalculateServer is the server API for Calculate service.
type CalculateServer interface {
	// Unary
	Add(context.Context, *Request) (*Response, error)
	// Server side streaming
	PrimeNoDecomposition(*PrimeNoDecompositionRequest, Calculate_PrimeNoDecompositionServer) error
	// client side streaming
	GetAvg(Calculate_GetAvgServer) error
}

// UnimplementedCalculateServer can be embedded to have forward compatible implementations.
type UnimplementedCalculateServer struct {
}

func (*UnimplementedCalculateServer) Add(ctx context.Context, req *Request) (*Response, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Add not implemented")
}
func (*UnimplementedCalculateServer) PrimeNoDecomposition(req *PrimeNoDecompositionRequest, srv Calculate_PrimeNoDecompositionServer) error {
	return status.Errorf(codes.Unimplemented, "method PrimeNoDecomposition not implemented")
}
func (*UnimplementedCalculateServer) GetAvg(srv Calculate_GetAvgServer) error {
	return status.Errorf(codes.Unimplemented, "method GetAvg not implemented")
}

func RegisterCalculateServer(s *grpc.Server, srv CalculateServer) {
	s.RegisterService(&_Calculate_serviceDesc, srv)
}

func _Calculate_Add_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(Request)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(CalculateServer).Add(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/Calculate/Add",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(CalculateServer).Add(ctx, req.(*Request))
	}
	return interceptor(ctx, in, info, handler)
}

func _Calculate_PrimeNoDecomposition_Handler(srv interface{}, stream grpc.ServerStream) error {
	m := new(PrimeNoDecompositionRequest)
	if err := stream.RecvMsg(m); err != nil {
		return err
	}
	return srv.(CalculateServer).PrimeNoDecomposition(m, &calculatePrimeNoDecompositionServer{stream})
}

type Calculate_PrimeNoDecompositionServer interface {
	Send(*PrimeNoDecompositionResponse) error
	grpc.ServerStream
}

type calculatePrimeNoDecompositionServer struct {
	grpc.ServerStream
}

func (x *calculatePrimeNoDecompositionServer) Send(m *PrimeNoDecompositionResponse) error {
	return x.ServerStream.SendMsg(m)
}

func _Calculate_GetAvg_Handler(srv interface{}, stream grpc.ServerStream) error {
	return srv.(CalculateServer).GetAvg(&calculateGetAvgServer{stream})
}

type Calculate_GetAvgServer interface {
	SendAndClose(*GetAvgResponse) error
	Recv() (*GetAvgRequest, error)
	grpc.ServerStream
}

type calculateGetAvgServer struct {
	grpc.ServerStream
}

func (x *calculateGetAvgServer) SendAndClose(m *GetAvgResponse) error {
	return x.ServerStream.SendMsg(m)
}

func (x *calculateGetAvgServer) Recv() (*GetAvgRequest, error) {
	m := new(GetAvgRequest)
	if err := x.ServerStream.RecvMsg(m); err != nil {
		return nil, err
	}
	return m, nil
}

var _Calculate_serviceDesc = grpc.ServiceDesc{
	ServiceName: "Calculate",
	HandlerType: (*CalculateServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "Add",
			Handler:    _Calculate_Add_Handler,
		},
	},
	Streams: []grpc.StreamDesc{
		{
			StreamName:    "PrimeNoDecomposition",
			Handler:       _Calculate_PrimeNoDecomposition_Handler,
			ServerStreams: true,
		},
		{
			StreamName:    "GetAvg",
			Handler:       _Calculate_GetAvg_Handler,
			ClientStreams: true,
		},
	},
	Metadata: "calculator/calculatorpb/calculator.proto",
}
